version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
